# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [4]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(
    Path("./Resources/applicants_data.csv")
)

# Review the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [5]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [8]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=(["EIN", "NAME"]))

# Review the DataFrame
applicant_data_df[:5]

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [9]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

# Display the categorical variables list
display(categorical_variables)

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [11]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [12]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [18]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data, 
    columns = enc.get_feature_names_out(categorical_variables)
)

# Review the DataFrame
encoded_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [19]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat([applicant_data_df.drop(columns = categorical_variables), encoded_df], axis=1)

# Review the Dataframe
encoded_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [20]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df["IS_SUCCESSFUL"]

# Display a sample of y
y[:5]

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [21]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=["IS_SUCCESSFUL"])

# Review the features DataFrame
X[:5]

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [22]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [23]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [26]:
# Define the the number of inputs (features) to the model
number_input_features = len(X.iloc[0])

# Review the number of features
number_input_features

116

In [27]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [28]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  8

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

8

In [29]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  8

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

8

In [30]:
# Create the Sequential model instance
nn = Sequential()

In [31]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [32]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [33]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=number_output_neurons, activation="linear"))

In [34]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 936

 dense_1 (Dense)             (None, 8)                 72

 dense_2 (Dense)             (None, 1)                 9

=================================================================
Total params: 1,017
Trainable params: 1,017
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [35]:
# Compile the Sequential model
nn.compile(loss = "binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [36]:
# Fit the model using 50 epochs and the training data
moden = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 810us/step - loss: 1.7721 - accuracy: 0.5564
Epoch 2/50
804/804 [==============================] - 1s 792us/step - loss: 1.0223 - accuracy: 0.6396
Epoch 3/50
804/804 [==============================] - 1s 802us/step - loss: 0.7973 - accuracy: 0.6674
Epoch 4/50
804/804 [==============================] - 1s 805us/step - loss: 0.7562 - accuracy: 0.6773
Epoch 5/50
804/804 [==============================] - 1s 907us/step - loss: 0.7294 - accuracy: 0.6907
Epoch 6/50
804/804 [==============================] - 1s 847us/step - loss: 0.6892 - accuracy: 0.6941
Epoch 7/50
804/804 [==============================] - 1s 851us/step - loss: 0.6884 - accuracy: 0.7054
Epoch 8/50
804/804 [==============================] - 1s 835us/step - loss: 0.6662 - accuracy: 0.7143
Epoch 9/50
804/804 [==============================] - 1s 812us/step - loss: 0.6546 - accuracy: 0.7178
Epoch 10/50
804/804 [==============================] - 1s 865us/step - loss: 0.6634 - accuracy: 0.7205
Epoch 11/50
804/804 [==============================] - 1s 881us/step - loss: 0.6470 - accuracy: 0.7224
Epoch 12/50
804/804 [==============================] - 1s 811us/step - loss: 0.6465 - accuracy: 0.7243
Epoch 13/50
804/804 [==============================] - 1s 804us/step - loss: 0.6476 - accuracy: 0.7156
Epoch 14/50
804/804 [==============================] - 1s 823us/step - loss: 0.6440 - accuracy: 0.7204
Epoch 15/50
804/804 [==============================] - 1s 846us/step - loss: 0.6361 - accuracy: 0.7214
Epoch 16/50
804/804 [==============================] - 1s 826us/step - loss: 0.6346 - accuracy: 0.7228
Epoch 17/50
804/804 [==============================] - 1s 853us/step - loss: 0.6306 - accuracy: 0.7234
Epoch 18/50
804/804 [==============================] - 1s 832us/step - loss: 0.6305 - accuracy: 0.7242
Epoch 19/50
804/804 [==============================] - 1s 855us/step - loss: 0.6257 - accuracy: 0.7214
Epoch 20/50
804/804 [==============================] - 1s 862us/step - loss: 0.6181 - accuracy: 0.7275
Epoch 21/50
804/804 [==============================] - 1s 879us/step - loss: 0.6264 - accuracy: 0.7224
Epoch 22/50
804/804 [==============================] - 1s 790us/step - loss: 0.6264 - accuracy: 0.7252
Epoch 23/50
804/804 [==============================] - 1s 833us/step - loss: 0.6189 - accuracy: 0.7263
Epoch 24/50
804/804 [==============================] - 1s 820us/step - loss: 0.6158 - accuracy: 0.7279
Epoch 25/50
804/804 [==============================] - 1s 797us/step - loss: 0.6131 - accuracy: 0.7274
Epoch 26/50
804/804 [==============================] - 1s 796us/step - loss: 0.6119 - accuracy: 0.7280
Epoch 27/50
804/804 [==============================] - 1s 888us/step - loss: 0.5913 - accuracy: 0.7280
Epoch 28/50
804/804 [==============================] - 1s 877us/step - loss: 0.5874 - accuracy: 0.7287
Epoch 29/50
804/804 [==============================] - 1s 889us/step - loss: 0.5896 - accuracy: 0.7308
Epoch 30/50
804/804 [==============================] - 1s 822us/step - loss: 0.5859 - accuracy: 0.7307
Epoch 31/50
804/804 [==============================] - 1s 851us/step - loss: 0.5895 - accuracy: 0.7296
Epoch 32/50
804/804 [==============================] - 1s 817us/step - loss: 0.5915 - accuracy: 0.7269
Epoch 33/50
804/804 [==============================] - 1s 814us/step - loss: 0.6013 - accuracy: 0.7255
Epoch 34/50
804/804 [==============================] - 1s 877us/step - loss: 0.5902 - accuracy: 0.7277
Epoch 35/50
804/804 [==============================] - 1s 835us/step - loss: 0.5843 - accuracy: 0.7315
Epoch 36/50
804/804 [==============================] - 1s 826us/step - loss: 0.5960 - accuracy: 0.7166
Epoch 37/50
804/804 [==============================] - 1s 936us/step - loss: 0.5877 - accuracy: 0.7308
Epoch 38/50
804/804 [==============================] - 1s 832us/step - loss: 0.5923 - accuracy: 0.7286
Epoch 39/50
804/804 [==============================] - 1s 855us/step - loss: 0.5840 - accuracy: 0.7332
Epoch 40/50
804/804 [==============================] - 1s 797us/step - loss: 0.5974 - accuracy: 0.7277
Epoch 41/50
804/804 [==============================] - 1s 795us/step - loss: 0.5881 - accuracy: 0.7312
Epoch 42/50
804/804 [==============================] - 1s 855us/step - loss: 0.5867 - accuracy: 0.7327
Epoch 43/50
804/804 [==============================] - 1s 803us/step - loss: 0.5902 - accuracy: 0.7315
Epoch 44/50
804/804 [==============================] - 1s 804us/step - loss: 0.5885 - accuracy: 0.7321
Epoch 45/50
804/804 [==============================] - 1s 809us/step - loss: 0.5857 - accuracy: 0.7336
Epoch 46/50
804/804 [==============================] - 1s 814us/step - loss: 0.5836 - accuracy: 0.7332
Epoch 47/50
804/804 [==============================] - 1s 810us/step - loss: 0.5894 - accuracy: 0.7335
Epoch 48/50
804/804 [==============================] - 1s 804us/step - loss: 0.5942 - accuracy: 0.7297
Epoch 49/50
804/804 [==============================] - 1s 809us/step - loss: 0.5835 - accuracy: 0.7328
Epoch 50/50
804/804 [==============================] - 1s 794us/step - loss: 0.5877 - accuracy: 0.7307

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [37]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.6097 - accuracy: 0.7278 - 277ms/epoch - 1ms/step
Loss: 0.6097435355186462, Accuracy: 0.7278134226799011

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [38]:
# Set the model's file path
file_path = Path("./Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [39]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [40]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [41]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 10

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

10

In [42]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [45]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu"))


# Output layer
nn_A1.add(Dense(units=number_output_neurons_A1, activation="linear"))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 10)                1170

 dense_4 (Dense)             (None, 1)                 11

 dense_5 (Dense)             (None, 10)                20

 dense_6 (Dense)             (None, 1)                 11

 dense_7 (Dense)             (None, 10)                20

 dense_8 (Dense)             (None, 1)                 11

=================================================================
Total params: 1,243
Trainable params: 1,243
Non-trainable params: 0
_________________________________________________________________

In [47]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [48]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 952us/step - loss: 0.7018 - accuracy: 0.6689
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6089 - accuracy: 0.7178
Epoch 3/50
804/804 [==============================] - 1s 916us/step - loss: 0.5998 - accuracy: 0.7145
Epoch 4/50
804/804 [==============================] - 1s 884us/step - loss: 0.5914 - accuracy: 0.7210
Epoch 5/50
804/804 [==============================] - 1s 922us/step - loss: 0.5886 - accuracy: 0.7208
Epoch 6/50
804/804 [==============================] - 1s 900us/step - loss: 0.5852 - accuracy: 0.7216
Epoch 7/50
804/804 [==============================] - 1s 994us/step - loss: 0.5865 - accuracy: 0.7227
Epoch 8/50
804/804 [==============================] - 1s 971us/step - loss: 0.5851 - accuracy: 0.7236
Epoch 9/50
804/804 [==============================] - 1s 867us/step - loss: 0.5813 - accuracy: 0.7254
Epoch 10/50
804/804 [==============================] - 1s 879us/step - loss: 0.5774 - accuracy: 0.7259
Epoch 11/50
804/804 [==============================] - 1s 922us/step - loss: 0.5847 - accuracy: 0.7261
Epoch 12/50
804/804 [==============================] - 1s 972us/step - loss: 0.5786 - accuracy: 0.7283
Epoch 13/50
804/804 [==============================] - 1s 913us/step - loss: 0.5832 - accuracy: 0.7208
Epoch 14/50
804/804 [==============================] - 1s 863us/step - loss: 0.5737 - accuracy: 0.7245
Epoch 15/50
804/804 [==============================] - 1s 895us/step - loss: 0.5731 - accuracy: 0.7286
Epoch 16/50
804/804 [==============================] - 1s 880us/step - loss: 0.5724 - accuracy: 0.7300
Epoch 17/50
804/804 [==============================] - 1s 926us/step - loss: 0.5758 - accuracy: 0.7310
Epoch 18/50
804/804 [==============================] - 1s 872us/step - loss: 0.5741 - accuracy: 0.7313
Epoch 19/50
804/804 [==============================] - 1s 948us/step - loss: 0.5731 - accuracy: 0.7302
Epoch 20/50
804/804 [==============================] - 1s 907us/step - loss: 0.5723 - accuracy: 0.7306
Epoch 21/50
804/804 [==============================] - 1s 964us/step - loss: 0.5785 - accuracy: 0.7262
Epoch 22/50
804/804 [==============================] - 1s 863us/step - loss: 0.5713 - accuracy: 0.7317
Epoch 23/50
804/804 [==============================] - 1s 907us/step - loss: 0.5709 - accuracy: 0.7318
Epoch 24/50
804/804 [==============================] - 1s 874us/step - loss: 0.5709 - accuracy: 0.7318
Epoch 25/50
804/804 [==============================] - 1s 890us/step - loss: 0.5742 - accuracy: 0.7323
Epoch 26/50
804/804 [==============================] - 1s 905us/step - loss: 0.5717 - accuracy: 0.7322
Epoch 27/50
804/804 [==============================] - 1s 915us/step - loss: 0.5704 - accuracy: 0.7322
Epoch 28/50
804/804 [==============================] - 1s 912us/step - loss: 0.5734 - accuracy: 0.7327
Epoch 29/50
804/804 [==============================] - 1s 875us/step - loss: 0.5701 - accuracy: 0.7330
Epoch 30/50
804/804 [==============================] - 1s 880us/step - loss: 0.5702 - accuracy: 0.7329
Epoch 31/50
804/804 [==============================] - 1s 870us/step - loss: 0.5698 - accuracy: 0.7323
Epoch 32/50
804/804 [==============================] - 1s 856us/step - loss: 0.5713 - accuracy: 0.7328
Epoch 33/50
804/804 [==============================] - 1s 922us/step - loss: 0.5708 - accuracy: 0.7326
Epoch 34/50
804/804 [==============================] - 1s 899us/step - loss: 0.5720 - accuracy: 0.7327
Epoch 35/50
804/804 [==============================] - 1s 873us/step - loss: 0.5697 - accuracy: 0.7328
Epoch 36/50
804/804 [==============================] - 1s 877us/step - loss: 0.5686 - accuracy: 0.7331
Epoch 37/50
804/804 [==============================] - 1s 870us/step - loss: 0.5693 - accuracy: 0.7328
Epoch 38/50
804/804 [==============================] - 1s 903us/step - loss: 0.5711 - accuracy: 0.7347
Epoch 39/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5692 - accuracy: 0.7332
Epoch 40/50
804/804 [==============================] - 1s 851us/step - loss: 0.5694 - accuracy: 0.7343
Epoch 41/50
804/804 [==============================] - 1s 866us/step - loss: 0.5694 - accuracy: 0.7342
Epoch 42/50
804/804 [==============================] - 1s 905us/step - loss: 0.5732 - accuracy: 0.7333
Epoch 43/50
804/804 [==============================] - 1s 908us/step - loss: 0.5691 - accuracy: 0.7334
Epoch 44/50
804/804 [==============================] - 1s 907us/step - loss: 0.5767 - accuracy: 0.7185
Epoch 45/50
804/804 [==============================] - 1s 912us/step - loss: 0.5674 - accuracy: 0.7331
Epoch 46/50
804/804 [==============================] - 1s 925us/step - loss: 0.5664 - accuracy: 0.7336
Epoch 47/50
804/804 [==============================] - 1s 865us/step - loss: 0.5662 - accuracy: 0.7337
Epoch 48/50
804/804 [==============================] - 1s 859us/step - loss: 0.5662 - accuracy: 0.7330
Epoch 49/50
804/804 [==============================] - 1s 891us/step - loss: 0.5661 - accuracy: 0.7337
Epoch 50/50
804/804 [==============================] - 1s 880us/step - loss: 0.5663 - accuracy: 0.7343

#### Alternative Model 2

In [49]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [50]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [51]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 8

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

8

In [52]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [53]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation="relu"))

# Output layer
nn_A2.add(Dense(units=number_output_neurons_A2, activation="linear"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 8)                 936

 dense_10 (Dense)            (None, 1)                 9

=================================================================
Total params: 945
Trainable params: 945
Non-trainable params: 0
_________________________________________________________________

In [56]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [57]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 1s 875us/step - loss: 5.6332 - accuracy: 0.5010
Epoch 2/100
804/804 [==============================] - 1s 942us/step - loss: 2.2028 - accuracy: 0.6293
Epoch 3/100
804/804 [==============================] - 1s 889us/step - loss: 2.0423 - accuracy: 0.6416
Epoch 4/100
804/804 [==============================] - 1s 875us/step - loss: 1.7614 - accuracy: 0.6601
Epoch 5/100
804/804 [==============================] - 1s 962us/step - loss: 1.6172 - accuracy: 0.6647
Epoch 6/100
804/804 [==============================] - 1s 958us/step - loss: 1.4893 - accuracy: 0.6692
Epoch 7/100
804/804 [==============================] - 1s 895us/step - loss: 1.3290 - accuracy: 0.6734
Epoch 8/100
804/804 [==============================] - 1s 827us/step - loss: 1.2865 - accuracy: 0.6740
Epoch 9/100
804/804 [==============================] - 1s 828us/step - loss: 1.2495 - accuracy: 0.6926
Epoch 10/100
804/804 [==============================] - 1s 827us/step - loss: 1.1920 - accuracy: 0.7034
Epoch 11/100
804/804 [==============================] - 1s 860us/step - loss: 1.1854 - accuracy: 0.7042
Epoch 12/100
804/804 [==============================] - 1s 880us/step - loss: 1.1724 - accuracy: 0.6993
Epoch 13/100
804/804 [==============================] - 1s 827us/step - loss: 1.1521 - accuracy: 0.6936
Epoch 14/100
804/804 [==============================] - 1s 814us/step - loss: 1.1374 - accuracy: 0.7010
Epoch 15/100
804/804 [==============================] - 1s 849us/step - loss: 1.1642 - accuracy: 0.7013
Epoch 16/100
804/804 [==============================] - 1s 849us/step - loss: 1.2465 - accuracy: 0.6931
Epoch 17/100
804/804 [==============================] - 1s 843us/step - loss: 1.1326 - accuracy: 0.6968
Epoch 18/100
804/804 [==============================] - 1s 889us/step - loss: 1.2596 - accuracy: 0.6817
Epoch 19/100
804/804 [==============================] - 1s 829us/step - loss: 1.5305 - accuracy: 0.6668
Epoch 20/100
804/804 [==============================] - 1s 828us/step - loss: 1.3776 - accuracy: 0.6804
Epoch 21/100
804/804 [==============================] - 1s 810us/step - loss: 1.1621 - accuracy: 0.6986
Epoch 22/100
804/804 [==============================] - 1s 812us/step - loss: 1.1591 - accuracy: 0.7042
Epoch 23/100
804/804 [==============================] - 1s 819us/step - loss: 1.1469 - accuracy: 0.6989
Epoch 24/100
804/804 [==============================] - 1s 966us/step - loss: 1.1408 - accuracy: 0.7006
Epoch 25/100
804/804 [==============================] - 1s 807us/step - loss: 1.1239 - accuracy: 0.7047
Epoch 26/100
804/804 [==============================] - 1s 797us/step - loss: 1.1197 - accuracy: 0.7063
Epoch 27/100
804/804 [==============================] - 1s 802us/step - loss: 1.0707 - accuracy: 0.7074
Epoch 28/100
804/804 [==============================] - 1s 861us/step - loss: 1.0625 - accuracy: 0.6996
Epoch 29/100
804/804 [==============================] - 1s 817us/step - loss: 1.0272 - accuracy: 0.7109
Epoch 30/100
804/804 [==============================] - 1s 906us/step - loss: 1.0335 - accuracy: 0.7111
Epoch 31/100
804/804 [==============================] - 1s 862us/step - loss: 1.0285 - accuracy: 0.7089
Epoch 32/100
804/804 [==============================] - 1s 891us/step - loss: 1.0205 - accuracy: 0.7123
Epoch 33/100
804/804 [==============================] - 1s 816us/step - loss: 1.0049 - accuracy: 0.7130
Epoch 34/100
804/804 [==============================] - 1s 827us/step - loss: 1.0099 - accuracy: 0.7096
Epoch 35/100
804/804 [==============================] - 1s 822us/step - loss: 1.0150 - accuracy: 0.7064
Epoch 36/100
804/804 [==============================] - 1s 804us/step - loss: 1.0054 - accuracy: 0.7088
Epoch 37/100
804/804 [==============================] - 1s 865us/step - loss: 1.0070 - accuracy: 0.7121
Epoch 38/100
804/804 [==============================] - 1s 888us/step - loss: 0.9975 - accuracy: 0.7158
Epoch 39/100
804/804 [==============================] - 1s 837us/step - loss: 1.0068 - accuracy: 0.7118
Epoch 40/100
804/804 [==============================] - 1s 810us/step - loss: 0.9981 - accuracy: 0.7117
Epoch 41/100
804/804 [==============================] - 1s 796us/step - loss: 0.9947 - accuracy: 0.7143
Epoch 42/100
804/804 [==============================] - 1s 838us/step - loss: 1.0555 - accuracy: 0.7051
Epoch 43/100
804/804 [==============================] - 1s 910us/step - loss: 1.0178 - accuracy: 0.7088
Epoch 44/100
804/804 [==============================] - 1s 863us/step - loss: 1.0235 - accuracy: 0.7024
Epoch 45/100
804/804 [==============================] - 1s 899us/step - loss: 0.9968 - accuracy: 0.7140
Epoch 46/100
804/804 [==============================] - 1s 985us/step - loss: 0.9995 - accuracy: 0.7133
Epoch 47/100
804/804 [==============================] - 1s 909us/step - loss: 0.9972 - accuracy: 0.7140
Epoch 48/100
804/804 [==============================] - 1s 980us/step - loss: 1.0143 - accuracy: 0.7102
Epoch 49/100
804/804 [==============================] - 1s 921us/step - loss: 1.0000 - accuracy: 0.7101
Epoch 50/100
804/804 [==============================] - 1s 916us/step - loss: 1.0004 - accuracy: 0.7131
Epoch 51/100
804/804 [==============================] - 1s 872us/step - loss: 1.0111 - accuracy: 0.7094
Epoch 52/100
804/804 [==============================] - 1s 807us/step - loss: 0.9961 - accuracy: 0.7133
Epoch 53/100
804/804 [==============================] - 1s 829us/step - loss: 1.0212 - accuracy: 0.6955
Epoch 54/100
804/804 [==============================] - 1s 865us/step - loss: 1.0017 - accuracy: 0.7093
Epoch 55/100
804/804 [==============================] - 1s 873us/step - loss: 1.0041 - accuracy: 0.7097
Epoch 56/100
804/804 [==============================] - 1s 828us/step - loss: 1.0011 - accuracy: 0.7131
Epoch 57/100
804/804 [==============================] - 1s 804us/step - loss: 1.0072 - accuracy: 0.7084
Epoch 58/100
804/804 [==============================] - 1s 800us/step - loss: 1.0029 - accuracy: 0.7099
Epoch 59/100
804/804 [==============================] - 1s 809us/step - loss: 0.9985 - accuracy: 0.7139
Epoch 60/100
804/804 [==============================] - 1s 861us/step - loss: 0.9959 - accuracy: 0.7142
Epoch 61/100
804/804 [==============================] - 1s 860us/step - loss: 0.9981 - accuracy: 0.7130
Epoch 62/100
804/804 [==============================] - 1s 804us/step - loss: 0.9985 - accuracy: 0.7143
Epoch 63/100
804/804 [==============================] - 1s 797us/step - loss: 0.9968 - accuracy: 0.7136
Epoch 64/100
804/804 [==============================] - 1s 913us/step - loss: 1.0040 - accuracy: 0.7112
Epoch 65/100
804/804 [==============================] - 1s 824us/step - loss: 0.9955 - accuracy: 0.7144
Epoch 66/100
804/804 [==============================] - 1s 818us/step - loss: 0.9974 - accuracy: 0.7131
Epoch 67/100
804/804 [==============================] - 1s 893us/step - loss: 0.9986 - accuracy: 0.7154
Epoch 68/100
804/804 [==============================] - 1s 820us/step - loss: 0.9958 - accuracy: 0.7149
Epoch 69/100
804/804 [==============================] - 1s 820us/step - loss: 0.9971 - accuracy: 0.7141
Epoch 70/100
804/804 [==============================] - 1s 817us/step - loss: 1.0055 - accuracy: 0.7149
Epoch 71/100
804/804 [==============================] - 1s 814us/step - loss: 0.9986 - accuracy: 0.7155
Epoch 72/100
804/804 [==============================] - 1s 812us/step - loss: 0.9966 - accuracy: 0.7144
Epoch 73/100
804/804 [==============================] - 1s 870us/step - loss: 1.0008 - accuracy: 0.7144
Epoch 74/100
804/804 [==============================] - 1s 807us/step - loss: 0.9981 - accuracy: 0.7143
Epoch 75/100
804/804 [==============================] - 1s 847us/step - loss: 0.9988 - accuracy: 0.7113
Epoch 76/100
804/804 [==============================] - 1s 842us/step - loss: 0.9980 - accuracy: 0.7127
Epoch 77/100
804/804 [==============================] - 1s 813us/step - loss: 0.9936 - accuracy: 0.7151
Epoch 78/100
804/804 [==============================] - 1s 829us/step - loss: 0.9942 - accuracy: 0.7138
Epoch 79/100
804/804 [==============================] - 1s 901us/step - loss: 0.9946 - accuracy: 0.7153
Epoch 80/100
804/804 [==============================] - 1s 859us/step - loss: 0.9931 - accuracy: 0.7159
Epoch 81/100
804/804 [==============================] - 1s 826us/step - loss: 0.9921 - accuracy: 0.7161
Epoch 82/100
804/804 [==============================] - 1s 831us/step - loss: 0.9936 - accuracy: 0.7153
Epoch 83/100
804/804 [==============================] - 1s 842us/step - loss: 0.9949 - accuracy: 0.7151
Epoch 84/100
804/804 [==============================] - 1s 814us/step - loss: 0.9939 - accuracy: 0.7146
Epoch 85/100
804/804 [==============================] - 1s 859us/step - loss: 0.9973 - accuracy: 0.7148
Epoch 86/100
804/804 [==============================] - 1s 819us/step - loss: 0.9959 - accuracy: 0.7168
Epoch 87/100
804/804 [==============================] - 1s 814us/step - loss: 1.0060 - accuracy: 0.7149
Epoch 88/100
804/804 [==============================] - 1s 810us/step - loss: 1.0033 - accuracy: 0.7126
Epoch 89/100
804/804 [==============================] - 1s 878us/step - loss: 0.9943 - accuracy: 0.7164
Epoch 90/100
804/804 [==============================] - 1s 891us/step - loss: 1.0067 - accuracy: 0.7031
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.9855 - accuracy: 0.7154
Epoch 92/100
804/804 [==============================] - 1s 900us/step - loss: 0.9837 - accuracy: 0.7134
Epoch 93/100
804/804 [==============================] - 1s 913us/step - loss: 0.9788 - accuracy: 0.7150
Epoch 94/100
804/804 [==============================] - 1s 959us/step - loss: 0.9735 - accuracy: 0.7168
Epoch 95/100
804/804 [==============================] - 1s 898us/step - loss: 0.9761 - accuracy: 0.7158
Epoch 96/100
804/804 [==============================] - 1s 849us/step - loss: 0.9757 - accuracy: 0.7158
Epoch 97/100
804/804 [==============================] - 1s 933us/step - loss: 0.9762 - accuracy: 0.7164
Epoch 98/100
804/804 [==============================] - 1s 813us/step - loss: 0.9865 - accuracy: 0.7088
Epoch 99/100
804/804 [==============================] - 1s 820us/step - loss: 0.9732 - accuracy: 0.7154
Epoch 100/100
804/804 [==============================] - 1s 803us/step - loss: 0.9744 - accuracy: 0.7161

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [58]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.6097 - accuracy: 0.7278 - 159ms/epoch - 593us/step
Loss: 0.6097435355186462, Accuracy: 0.7278134226799011

In [59]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 0.5772 - accuracy: 0.7293 - 281ms/epoch - 1ms/step
Loss: 0.5772093534469604, Accuracy: 0.7293294668197632

In [61]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 1.0014 - accuracy: 0.7110 - 245ms/epoch - 912us/step
Loss: 1.0014405250549316, Accuracy: 0.7110204100608826

### Step 3: Save each of your alternative models as an HDF5 file.

In [62]:
# Set the file path for the first alternative model
file_path = Path("./Resources/AlphabetSoupA1.h5")

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [63]:
# Set the file path for the second alternative model
file_path = Path("./Resources/AlphabetSoupA2.h5")

# Export your model to a HDF5 file
nn_A2.save(file_path)